const CATEGORIES_NAMESPACE = 'CATEGORIES:';

export const GET_CATEGORIES: string = `${CATEGORIES_NAMESPACE}GET`;
export const DELETE_CATEGORY: string = `${CATEGORIES_NAMESPACE}DELETE`;
export const CREATE_CATEGORY: string = `${CATEGORIES_NAMESPACE}CREATE`;
export const LINK_CATEGORIES: string = `${CATEGORIES_NAMESPACE}LINK`;
export const UNLINK_CATEGORIES: string = `${CATEGORIES_NAMESPACE}UNLINK`;
export const REQUEST_CATEGORIES: string = `${CATEGORIES_NAMESPACE}REQUEST`;
