const WORDS_NAMESPACE = 'WORDS:';

export const FETCH_WORDS_OFFSET: string = `${WORDS_NAMESPACE}FETCH_WITH_OFFSET`;
export const FETCH_WORDS_OFFSET_REQUEST: string = `${WORDS_NAMESPACE}FETCH_WITH_OFFSET_REQUEST`;
