const WORDS_NAMESPACE = 'WORDS:';

export const FETCH_WORDS_OFFSET: string = `${WORDS_NAMESPACE}FETCH_WITH_OFFSET`;
export const APPEND_WORD_TO_LIST: string = `${WORDS_NAMESPACE}APPEND_WORD_TO_LIST`;
export const DELETE_WORDS_OFFSET: string = `${WORDS_NAMESPACE}DELETE_WORDS_OFFSET`;
export const FETCH_WORDS_OFFSET_REQUEST: string = `${WORDS_NAMESPACE}FETCH_WITH_OFFSET_REQUEST`;
